package com.example.jonalnb.industriel;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.widget.Toast;

/**
 * Created by JonaLNB on 23/03/2017.
 */

public class BDMaquinaria extends SQLiteOpenHelper {
    String SQL = "create table maquinas(id int primary key, nombre varchar(60), uso varchar(500), imagen int)";
    public BDMaquinaria(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    public void onCreate(SQLiteDatabase db) {
        db.execSQL(SQL);
        SQL = "INSERT INTO maquinas(id, nombre, uso, imagen) VALUES" +
                "(00000,'Pulidora',' El pulido es la eliminación de metal con un disco abrasivo giratorio que trabaja como una fresadora de corte. El disco está compuesto por un gran número de granos de material abrasivo conglomerado, en que cada grano actúa como un útil de corte minúsculo. Con este proceso se consiguen superficies muy suaves y precisas Dado que sólo se elimina una parte pequeña del material con cada pasada del disco, las pulidoras requieren una regulación muy precisa. La presión del disco sobre la pieza se selecciona con mucha exactitud, por lo que pueden tratarse de esta forma materiales frágiles que no pueden procesarse con otros dispositivos convencionales.',"+R.mipmap.pulidora+")," +
                "(00001,'Torno','El torno, la máquina giratoria más común y más antigua, sujeta una pieza de metal o de madera y la hace girar mientras un útil de corte da forma al objeto. El útil puede moverse paralela o perpendicularmente a la dirección de giro, para obtener piezas con partes cilíndricas o cónicas, o para cortar acanaladuras. Empleando útiles especiales un torno puede utilizarse también para obtener superficies listas, como las producidas por una fresadora, o para taladrar orificios en la pieza.', "+R.mipmap.torno+"), " +
                "(00002,'Prensa','Las prensas dan forma a las piezas sin eliminar material, o sea, sin producir viruta. Una prensa consta de un marco que sostiene una bancada fija, un pistón, una fuente de energía y un mecanismo que mueve el pistón en paralelo o en ángulo recto con respecto a la bancada. Las prensas cuentan con troqueles y punzones que permiten deformar, perforar y cizallar las piezas. Estas máquinas pueden producir piezas a gran velocidad porque el tiempo que requiere cada proceso es sólo el tiempo de desplazamiento del pistón. ', "+R.mipmap.prensa+"), " +
                "(00003,'Taladro','El taladrado es la operación de mecanizado, destinada a producir agujeros cilíndricos, pasantes o ciegos, generalmente en medio del material, la operación del tala-drado puede llevarse a cabo, igualmente en tornos, fresadoras o mandriladoras. La herramienta utilizada, llamada broca o taladro, presenta, generalmente, dos líneas de corte en hélice. Esta herramienta se fija en el husillo de la taladradora de manera que su eje coincida exactamente con el eje de rotación del propio husillo. Arrastrado por esté, el útil gira sobre si mismo alrededor de su eje longitudinal(movimiento de corte)y avanza axialmente dentro de la pieza a taladrar (movimiento de avance). La velocidad de la rotación de la broca debe ser tal que la velocidad lineal del punto de la arista más alejado del eje sea compatible con la velocidad de corte del material mecanizado. ',"+R.mipmap.taladro+"), " +
                "(00004,'Limadora','Máquina-herramienta acepilladora, en la cual el movimiento de corte se obtiene por desplazamiento del útil. Una limadora está compuesta de una bancada, que sostiene una mesa porta piezas móviles en un plano vertical, posee un movimiento alternativo perpendicular a dicho plano por medio de una biela de corredera movida por un volante de manivela.',"+R.mipmap.limadora+"), " +
                "(00005,'Mandrinadora','Máquina-herramienta para el mecanizado, mediante el arranque de viruta de la pared o el borde de un agujero ya perforado. Una mandriladora está compuesta especialmente por una herramienta giratoria y una mesa sobre la cual se fija la pieza que debe ser mecanizada; estos dos elementos pueden desplazarse el uno con respecto al otro, sea para realizar los ajustes previos, sea para el mecanizado propiamente dicho. Según las máquinas, su eje de trabajo es horizontal o vertical.',"+R.mipmap.mandrinadora+"), " +
                "(00006,'Fresadora','En las fresadoras, la pieza entra en contacto con un dispositivo circular que cuenta con varios puntos de corte. La pieza se sujeta a un soporte que controla el avance de la pieza contra el útil de corte. El soporte puede avanzar en tres direcciones: longitudinal, horizontal y vertical. En algunos casos también puede girar. Las fresadoras son las máquinas herramientas más versátiles. Permiten obtener superficies curvadas con un alto grado de precisión y un acabado excelente. Los distintos tipos de útiles de corte permiten obtener ángulos, ranuras, engranajes o muescas.', "+R.mipmap.fresadora+")," +
                "(00007,'Impresora 3D','Una impresora 3D es una máquina capaz de realizar réplicas de diseños en 3D, creando piezas o maquetas volumétricas a partir de un diseño hecho por ordenador, descargado de internet o recogido a partir de un escáner 3D. Surgen con la idea de convertir archivos de 2D en prototipos reales o 3D.',"+R.mipmap.impresora+")," +
                "(00008,'Perfiladora','La perfiladora se utiliza para obtener superficies lisas. El útil se desliza sobre una pieza fija y efectúa un primer recorrido para cortar salientes, volviendo a la posición original para realizar el mismo recorrido tras un breve desplazamiento lateral. Esta máquina utiliza un útil de una sola punta y es lenta, porque depende de lo recorridos que se efectúen hacia adelante y hacia atrás. Por esta razón no se suele utilizar en las líneas de producción, pero sí en fábricas de herramientas y troqueles o en talleres que fabrican series pequeñas y que requieren mayor flexibilidad.',"+R.mipmap.perfiladora+")," +
                "(00009,'Cepilladora','Esta es la mayor de las máquinas herramientas de vaivén. Al contrario que en las perfiladoras, donde el útil se mueve sobre una pieza fija, la cepilladora mueve la pieza sobre un útil fijo. Después de cada vaivén, la pieza se mueve lateralmente para utilizar otra parte de la herramienta. Al igual que la perfiladora, la cepilladora permite hacer cortes verticales, horizontales o diagonales. También puede utilizar varios útiles a la vez para hacer varios cortes simultáneos.',"+R.mipmap.cepilladora+")," +
                "(00010,'Robot CRS F3','Encendido del robot.\\nEn primer lugar, ubicar los botones que integran la unidad de control del robot.\\nProcedimiento. \\nQuitar el paro de emergencia haciendo girar el botón en el sentido que marcan las flechas, tanto del control como del teach pendant.\\nPresionar botón de ON/OFF.\\nEsperar a que el control cargue el sistema operativo, cuando termine, aparecerá C500C CROS en el display del control.\\nPresionar el botón Arm Power para habilitar el robot, se encenderá una luz en el robot indicando que ya puede operarse.\\n\\nSeleccionar una aplicación. Estos son los botones del teach pendat que se usarán durante la práctica. Al encender el robot, se encenderá automáticamente el teach pendant, mostrando elmensaje de Main menú\\n Presionar el botón F1 para activar la función app.\\nAl abrir la función Application: Find, se mostrarán las aplicaciones existentes en la memoria del robot. Con el botón F1 se seleccionará la aplicación que aparece en pantalla. Para cambiar de aplicación se debe presionar F1 o F2.\\n\\nEdición y selección de variables.\\n\\nProcedimiento\\n En la pantalla de Application Edit presionar F1 para editar las variables. \\nSe mostrará en el display el número de variable que se puede editar. Al presionar F1 se escoge la variable. Al presionar F2 se borrará la variable, si se presiona este botón, se deberá escoger no para evitar que se borre. Al presionar F3 y F4 se puede cambiar de variable\\n  Al llegar al Manual menú ON podemos mover las articulaciones (Joints) del robot para empezar a enseñarle en donde deberá posicionarse.',"+R.mipmap.robot+")";
        db.execSQL(SQL);
    }

    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
